-- ============================================================================
-- Role and Permission Setup
-- Creates roles and grants appropriate permissions
-- ============================================================================

-- ============================================================================
-- Create Roles
-- ============================================================================

CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS DEVOPS;
CREATE ROLE IF NOT EXISTS READ_ONLY;

-- ============================================================================
-- Grant Database Permissions - DEV
-- ============================================================================

-- Data Engineer permissions on DEV
GRANT USAGE ON DATABASE DEV_RAW TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE DEV_RAW TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE DEV_STAGING TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE DEV_STAGING TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE DEV_DW TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE DEV_DW TO ROLE DATA_ENGINEER;

-- Data Analyst permissions on DEV
GRANT USAGE ON DATABASE DEV_RAW TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE DEV_STAGING TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE DEV_DW TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE DEV_RAW TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE DEV_STAGING TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE DEV_DW TO ROLE DATA_ANALYST;

-- ============================================================================
-- Grant Database Permissions - QA
-- ============================================================================

-- Data Engineer permissions on QA
GRANT USAGE ON DATABASE QA_RAW TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE QA_RAW TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE QA_STAGING TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE QA_STAGING TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE QA_DW TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE QA_DW TO ROLE DATA_ENGINEER;

-- Data Analyst permissions on QA
GRANT USAGE ON DATABASE QA_RAW TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE QA_STAGING TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE QA_DW TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE QA_RAW TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE QA_STAGING TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE QA_DW TO ROLE DATA_ANALYST;

-- ============================================================================
-- Grant Database Permissions - PROD
-- ============================================================================

-- Data Engineer permissions on PROD (more restrictive)
GRANT USAGE ON DATABASE PROD_RAW TO ROLE DATA_ENGINEER;
GRANT CREATE SCHEMA ON DATABASE PROD_RAW TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE PROD_STAGING TO ROLE DATA_ENGINEER;
GRANT CREATE SCHEMA ON DATABASE PROD_STAGING TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE PROD_DW TO ROLE DATA_ENGINEER;
GRANT CREATE SCHEMA ON DATABASE PROD_DW TO ROLE DATA_ENGINEER;

-- Data Analyst permissions on PROD (read-only)
GRANT USAGE ON DATABASE PROD_RAW TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE PROD_STAGING TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE PROD_DW TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE PROD_RAW TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE PROD_STAGING TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE PROD_DW TO ROLE DATA_ANALYST;

-- ============================================================================
-- Grant Schema Permissions (Future Grants)
-- ============================================================================

-- Future grants for Data Engineer
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEV_RAW.BRONZE TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEV_STAGING.SILVER TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEV_DW.DIMENSIONS TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DEV_DW.FACTS TO ROLE DATA_ENGINEER;

-- Future grants for Data Analyst
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_RAW.BRONZE TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_STAGING.SILVER TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_DW.DIMENSIONS TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_DW.FACTS TO ROLE DATA_ANALYST;

-- ============================================================================
-- Grant Utility Database Permissions
-- ============================================================================

GRANT USAGE ON DATABASE UTILITY TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE UTILITY TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE UTILITY TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL SCHEMAS IN DATABASE UTILITY TO ROLE DATA_ANALYST;

-- ============================================================================
-- Assign Roles to Users (Example - adjust as needed)
-- ============================================================================

-- Note: Replace 'your_user' with actual usernames
-- GRANT ROLE DATA_ENGINEER TO USER your_user;
-- GRANT ROLE DATA_ANALYST TO USER your_user;

