name: 'retail_data_warehouse'
version: '1.0.0'
config-version: 2

profile: 'retail_data_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_data_warehouse:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    dimensions:
      +materialized: table
      +schema: dimensions
    facts:
      +materialized: incremental
      +schema: facts
    marts:
      +materialized: table
      +schema: marts

vars:
  # Environment-specific variables
  environment: "{{ env_var('DBT_ENV', 'dev') }}"
  
  # Business logic variables
  scd_type_2_dimensions:
    - dim_customers
    - dim_products
    - dim_stores

  scd_type_1_dimensions:
    - dim_categories

